/**
 * Catalog Module — typed accessors for the static card/set/product data.
 *
 * All data is imported at build time from the JSON files generated by
 * the import-catalog script. No runtime fetching is needed.
 *
 * @module features/catalog
 */

import type {
  CardDefinition,
  CardGameplayMeta,
  SetDefinition,
  ProductDefinition,
  DropTable,
  Rarity,
  CardType,
  Supertype,
  Domain,
  ShowcaseVariant,
} from "@/types/game";

// ── Raw JSON imports ─────────────────────────────────────────────────

import setsData from "@/data/sets/sets.json";
import cardsData from "@/data/cards/cards.json";
import metaData from "@/data/cards/gameplay-meta.json";
import productsData from "@/data/products/products.json";

// ── Catalog version ──────────────────────────────────────────────────

/** ISO timestamp of when the catalog was last imported. */
export const catalogVersion: string = cardsData.catalogVersion;

// ── Type-safe casts ──────────────────────────────────────────────────
// The JSON data is untyped at import; we cast once here and build
// lookup indices so downstream code always gets typed data.

const allCards = cardsData.cards as unknown as CardDefinition[];
const allSets = setsData.sets as unknown as SetDefinition[];
const allMeta = metaData.meta as unknown as CardGameplayMeta[];
const allProducts = productsData.products as unknown as ProductDefinition[];
const allDropTables = productsData.dropTables as unknown as DropTable[];

// ── Lookup indices (built once at module load) ───────────────────────

const cardById = new Map<string, CardDefinition>();
const cardsBySet = new Map<string, CardDefinition[]>();
const cardsByRarity = new Map<Rarity, CardDefinition[]>();
const cardsByType = new Map<CardType, CardDefinition[]>();
const cardsBySupertype = new Map<Supertype, CardDefinition[]>();
const cardsByDomain = new Map<Domain, CardDefinition[]>();
const metaByCardId = new Map<string, CardGameplayMeta>();
const setByCode = new Map<string, SetDefinition>();
const productById = new Map<string, ProductDefinition>();
const productsBySet = new Map<string, ProductDefinition[]>();
const dropTableById = new Map<string, DropTable>();

function buildIndices() {
  for (const card of allCards) {
    cardById.set(card.id, card);

    // By set
    if (!cardsBySet.has(card.setCode)) cardsBySet.set(card.setCode, []);
    cardsBySet.get(card.setCode)!.push(card);

    // By rarity
    if (!cardsByRarity.has(card.rarity)) cardsByRarity.set(card.rarity, []);
    cardsByRarity.get(card.rarity)!.push(card);

    // By card type
    if (!cardsByType.has(card.cardType)) cardsByType.set(card.cardType, []);
    cardsByType.get(card.cardType)!.push(card);

    // By supertype
    if (card.supertype) {
      if (!cardsBySupertype.has(card.supertype))
        cardsBySupertype.set(card.supertype, []);
      cardsBySupertype.get(card.supertype)!.push(card);
    }

    // By domain
    for (const domain of card.domains) {
      if (!cardsByDomain.has(domain)) cardsByDomain.set(domain, []);
      cardsByDomain.get(domain)!.push(card);
    }
  }

  for (const m of allMeta) {
    metaByCardId.set(m.cardId, m);
  }

  for (const s of allSets) {
    setByCode.set(s.setCode, s);
  }

  for (const p of allProducts) {
    productById.set(p.id, p);
    if (!productsBySet.has(p.setCode)) productsBySet.set(p.setCode, []);
    productsBySet.get(p.setCode)!.push(p);
  }

  for (const dt of allDropTables) {
    dropTableById.set(dt.id, dt);
  }
}

buildIndices();

// ── Card accessors ───────────────────────────────────────────────────

/** Get all cards (656 total). */
export function getAllCards(): CardDefinition[] {
  return allCards;
}

/** Get a single card by its UUID. */
export function getCardById(id: string): CardDefinition | undefined {
  return cardById.get(id);
}

/** Get all cards belonging to a set (e.g. "OGN"). */
export function getCardsBySet(setCode: string): CardDefinition[] {
  return cardsBySet.get(setCode) ?? [];
}

/** Get all cards of a given rarity. */
export function getCardsByRarity(rarity: Rarity): CardDefinition[] {
  return cardsByRarity.get(rarity) ?? [];
}

/** Get all cards of a given card type. */
export function getCardsByType(cardType: CardType): CardDefinition[] {
  return cardsByType.get(cardType) ?? [];
}

/** Get all cards of a given supertype. */
export function getCardsBySupertype(supertype: Supertype): CardDefinition[] {
  return cardsBySupertype.get(supertype) ?? [];
}

/** Get all cards that include a given domain. */
export function getCardsByDomain(domain: Domain): CardDefinition[] {
  return cardsByDomain.get(domain) ?? [];
}

/**
 * Get base (non-showcase) cards for a set.
 * Useful for collection-completion tracking.
 */
export function getBaseCardsBySet(setCode: string): CardDefinition[] {
  return getCardsBySet(setCode).filter((c) => c.rarity !== "showcase");
}

/**
 * Get showcase variants for a set.
 */
export function getShowcaseCardsBySet(setCode: string): CardDefinition[] {
  return getCardsBySet(setCode).filter((c) => c.rarity === "showcase");
}

/**
 * Get showcase cards filtered by variant type.
 */
export function getCardsByShowcaseVariant(
  variant: ShowcaseVariant,
  setCode?: string,
): CardDefinition[] {
  const pool = setCode ? getCardsBySet(setCode) : allCards;
  return pool.filter(
    (c) => c.rarity === "showcase" && c.showcaseVariant === variant,
  );
}

// ── Gameplay meta accessors ──────────────────────────────────────────

/** Get gameplay meta for all cards. */
export function getAllGameplayMeta(): CardGameplayMeta[] {
  return allMeta;
}

/** Get gameplay meta for a single card. */
export function getGameplayMeta(cardId: string): CardGameplayMeta | undefined {
  return metaByCardId.get(cardId);
}

// ── Set accessors ────────────────────────────────────────────────────

/** Get all sets, sorted by release order. */
export function getAllSets(): SetDefinition[] {
  return allSets;
}

/** Get a single set by its code (e.g. "OGN"). */
export function getSetByCode(setCode: string): SetDefinition | undefined {
  return setByCode.get(setCode);
}

// ── Product accessors ────────────────────────────────────────────────

/** Get all products. */
export function getAllProducts(): ProductDefinition[] {
  return allProducts;
}

/** Get a single product by ID. */
export function getProductById(id: string): ProductDefinition | undefined {
  return productById.get(id);
}

/** Get all products for a given set. */
export function getProductsBySet(setCode: string): ProductDefinition[] {
  return productsBySet.get(setCode) ?? [];
}

// ── Drop table accessors ─────────────────────────────────────────────

/** Get all drop tables. */
export function getAllDropTables(): DropTable[] {
  return allDropTables;
}

/** Get a single drop table by ID. */
export function getDropTable(id: string): DropTable | undefined {
  return dropTableById.get(id);
}

/** Get the drop table for a specific product. Returns undefined for products without one. */
export function getDropTableForProduct(
  productId: string,
): DropTable | undefined {
  const product = productById.get(productId);
  if (!product?.dropTableId) return undefined;
  return dropTableById.get(product.dropTableId);
}

// ── Engine helpers ───────────────────────────────────────────────────
// Pre-built Maps that the engine functions need.

/** Map of productId → ProductDefinition. Used by engine functions. */
export function getProductMap(): Map<string, ProductDefinition> {
  return productById;
}

/** Map of productId → setCode. Used by engine functions. */
export function getProductSetMap(): Map<string, string> {
  const map = new Map<string, string>();
  for (const [id, p] of productById) {
    map.set(id, p.setCode);
  }
  return map;
}
